version: '3'

services:
  database:
    build: ./docker
    ports:
      - "5432:5432"
    volumes:
       - rust-patterns-ddd:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  rust-patterns-ddd:
